DEVS-809  2nd step of pool creation
hadeswap-solana/hadeswap-ui pull request #159
Opened 2022-12-07 13:33 UTC by Alexandr-Horton

## Description

fixed 2nd step of pool creation

## Environment link

[Link](https://hadeswap-git-DEVS-809-frakt.vercel.app/)

## Jira issue link

[DEVS-809](https://frakt-nft.atlassian.net/browse/DEVS-809)

2022-12-07 17:22 UTC, vladji commented on src/pages/CreatePool/index.tsx
> +  const [step, setStep] = useState<number>(market.marketPubkey ? 1 : 0);
это решение не будет корректно работать. теперь после загрузки маркета он будет лежать в сторе и если ты зайдешь на стр my pools и нажмешь там create pool, то маркет уже будет и сразу прыгнет на 2 шаг тоже

2022-12-08 08:34 UTC, Alexandr-Horton commented on src/pages/CreatePool/index.tsx
> +  const [step, setStep] = useState<number>(market.marketPubkey ? 1 : 0);
да действительно не заметил

2022-12-09 13:36 UTC, vladji commented on src/pages/CreatePool/components/StepsButtons.tsx
> +      history.push(createCreatePoolPickSideLink(chosenMarketKey));
я не понял, для чего это нужно и ниже тоже

2022-12-09 13:36 UTC, vladji commented on src/pages/CreatePool/components/StepOne.tsx
> +    history.push(createCreatePoolPickSideLink(marketPubkey));
зачем это? я попробовал, вроде все норм без этого работает, может чего не заметил?

2022-12-09 13:36 UTC, vladji commented on src/components/CreatePoolButton/CreatePoolButton.tsx
> +      onClick={onCreatePoolClick}
здесь можно было вообще эту функцию не писать и сделать так, мне кажется так лаконичнее
<NavLink to={`/create-pool/${marketPublicKey || ''}`}>
и все
и useCallback тут не нужен

2022-12-12 09:20 UTC, vladji requested changes

2022-12-12 09:20 UTC, vladji commented on src/pages/CreatePool/components/StepOne.tsx
> +    history.push(createCreatePoolPickSideLink(marketPubkey));
это пускай будет

2022-12-12 09:20 UTC, vladji commented on src/pages/CreatePool/components/StepsButtons.tsx
> +      history.push(createCreatePoolPickSideLink(chosenMarketKey));
а это не нужно, запутывает предназначение

2022-12-12 09:20 UTC, vladji commented on src/pages/CreatePool/components/StepsButtons.tsx
> +      step === 2 && history.push(createCreatePoolPickSideLink(chosenMarketKey));
и эти две строки тоже не нужны

2022-12-12 09:23 UTC, vladji commented on src/pages/CreatePool/index.tsx
>    useFetchMarket(chosenMarketKey);
и эту строку нужно удалить, она здесь не нужна

2022-12-13 12:48 UTC, vladji approved these changes

2022-12-13 12:54 UTC, merged