DEVS-835 fix: actual value in the buyOrderAmount field on edit pool
hadeswap-solana/hadeswap-ui pull request #189
Opened 2022-12-15 16:46 UTC by vladji

## Description

the actual value in the buyOrderAmount field when editing the pool

## Environment link

[Link](https://hadeswap-git-feature-devs-835-frakt.vercel.app/)

## Jira issue link

[DEVS-835](https://frakt-nft.atlassian.net/browse/DEVS-835)

2022-12-16 15:06 UTC, sablevsky requested changes
Еще раз:
nftsAmount или nftsCount -- это ордера на sell. Т.е. sellOrders. sellOrders.length === nftsCount === nftsAmount.
buyOrdersAmount -- ордероа на buy. Они существуют для LiquidityProvision и TokenForNft пуллов. И не существуют для NftForToken.
Сейчас все еще мешанина и работать не будет

2022-12-16 15:06 UTC, sablevsky commented on src/pages/EditPool/index.tsx
>        rawSpotPrice,
Тут непонятно.
buyOrdersAmount нужно обязательно для TokenForNft. Получается, что теперь нельзя отредачить TokenForNft пулл

2022-12-16 15:06 UTC, sablevsky commented on src/pages/EditPool/index.tsx
> +  const buyOrdersAmount = selectedNfts.length;
selectedNfts.length и buyOrdersAmount это не одно и то же

2022-12-23 12:48 UTC, Alexandr-Horton approved these changes

2022-12-26 14:59 UTC, sablevsky approved these changes

2022-12-26 15:56 UTC, Alexandr-Horton approved these changes

2022-12-27 11:35 UTC, merged