feat: Main Page Revamp, top 20
hadeswap-solana/hadeswap-ui pull request #39
Opened 2022-10-21 08:55 UTC by Alexandr-Horton

## Description

add top 20 list on main page

## Evironment link

[Link](https://hadeswap-git-feature/DEVS-670-frakt.vercel.app/)

2022-10-21 09:58 UTC, sablevsky requested changes

2022-10-21 09:58 UTC, sablevsky commented on src/components/TopMarkets/TopMarkets.tsx
> +  }, []);
сюда dispatch в зависимости нужен

2022-10-21 09:58 UTC, sablevsky commented on src/components/TopMarkets/TopMarkets.tsx
> +import React, { FC, useCallback, useEffect, useState } from 'react';
импорт реакта не нужен

2022-10-21 09:58 UTC, sablevsky commented on src/components/TopMarkets/TopMarkets.module.scss
> +  }
эта штука лишняя, думаю

2022-10-24 22:44 UTC, vladji commented on src/components/TopMarkets/TopMarkets.module.scss
> +  margin-bottom: 0px !important;
px лишнее, можно просто 0

2022-10-24 22:44 UTC, vladji commented on src/components/TopMarkets/TopMarkets.module.scss
> +  @media (max-width: 787px) {
481px — 768px for iPads & tablets
т.е. должно быть max-width: 768px
у меня там кое-где тоже была ошибка, но в новом ПР уже исправлено

2022-10-24 22:44 UTC, vladji commented on src/components/TopMarkets/TopMarkets.module.scss
> +  background: #94c5fd;
если этот цвет часто повторяется, может на него лучше завести переменную

2022-10-24 22:44 UTC, vladji commented on src/components/TopMarkets/TopMarkets.module.scss
> +  border: unset;
зачем тут это, если ниже прописан снова border

2022-10-24 22:44 UTC, vladji commented on src/components/TopMarkets/TopMarkets.module.scss
> +  cursor: pointer;
два раза одно и то же

2022-10-24 22:44 UTC, vladji commented on src/pages/HomePage/Home.tsx
> +        {/* <NavLink to={PATHS.COLLECTIONS}>
лично мое мнение: закомменченные куски кода лучше не оставлять, иначе они там остануться навсегда
@sablevsky, как считаешь?

2022-10-24 22:44 UTC, vladji commented on src/pages/HomePage/Home.module.scss
>    @media screen and (max-width: 767px) {
768px

2022-10-24 22:44 UTC, vladji commented on src/components/TopMarkets/TopMarkets.tsx
> +          <>
тут фрагмент не нужен

2022-10-24 22:52 UTC, vladji commented
там еще сколл вниз пустой будет из-за незаполненного грида, если например только 2 оффера будет, хотя это маловероятный кейс, но все же

2022-11-01 10:16 UTC, sablevsky commented
@Alexandr-Horton 
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/24393100/199211406-a706642b-2de4-4b03-8501-cd7f1d26bfad.png">

2022-11-01 10:16 UTC, sablevsky commented
нужно initialValue: []
или хэндлить, когда даты нет

2022-11-03 08:35 UTC, sablevsky requested changes

2022-11-03 08:35 UTC, sablevsky commented on src/pages/HomePage/Home.tsx
> +        {/* <NavLink to={PATHS.COLLECTIONS}>
Иногда -- полезно. Когда, например, перед релизом мы хотим что-то скрыть.
Но в общем случае -- да. Согласен. Лучше удалять

2022-11-03 08:35 UTC, sablevsky commented on src/components/TopMarkets/TopMarkets.tsx
> +}
как то я провтыкал твой IMarket
Переименуй, прошу)

2022-11-03 10:01 UTC, sablevsky approved these changes

2022-11-04 08:39 UTC, vladji commented on src/pages/HomePage/Home.tsx
> +
я может чего-то не знаю, но не понятно, зачем тут пустой массив

2022-11-04 08:46 UTC, vladji approved these changes

2022-11-30 13:00 UTC, closed without merging