Feature/devs 635
hadeswap-solana/hadeswap-ui pull request #47
Opened 2022-10-24 14:00 UTC by vladji

## Description

implemented cart sider on mobile

## Screenshots

## Environment link

[Link](https://hadeswap-git-feature-devs-635-frakt.vercel.app/)

## Jira issue link

[DEVS-635](https://frakt-nft.atlassian.net/browse/DEVS-635)

2022-10-24 14:31 UTC, sablevsky commented
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/24393100/197551271-5b2f90ac-cbf7-4f34-81fa-386849315dcb.png">

2022-10-24 15:04 UTC, sablevsky requested changes

2022-10-24 15:04 UTC, sablevsky commented on src/pages/Collections/Collections.tsx
> +  const screenMode = useSelector(selectScreeMode) as ScreenTypes;
опиши селектор, не через рамду. Тогда не нужно будет явно преобразовывать типы

2022-10-24 15:04 UTC, sablevsky commented on src/pages/Collections/Collections.tsx
>    const markets = useSelector(selectAllMarkets) as MarketInfo[];
тут явное преобразование не нужно

2022-10-24 15:04 UTC, sablevsky commented on src/pages/Collections/Collections.tsx
>    const collectionsLoading = useSelector(selectAllMarketsLoading) as boolean;
и тут

2022-10-24 15:04 UTC, sablevsky commented on src/pages/Collections/Collections.tsx
>    useEffect(() => {
диспатч в зависимости

2022-10-24 15:04 UTC, sablevsky commented on src/pages/Collections/Collections.tsx
> +  }, [searchStr, markets]);
С зависимостями беда совсем

2022-10-24 15:04 UTC, sablevsky commented on src/pages/Collections/Collections.tsx
>    }, [sortValue]);
Тут тоже.
Это вообще в юзмемо логичнее позаворачивать

2022-10-24 15:04 UTC, sablevsky commented on src/state/common/reducers.ts
>  });
На самом деле, мне не нравится управление мобилкой через стейт. Я б это делал через цсс. Ну да ладно, оставляем

2022-10-24 15:04 UTC, sablevsky commented on src/state/common/selectors.ts
>  );
тут лучше классически написать, чтоб типизация ложилась нормально

2022-10-24 15:04 UTC, sablevsky commented on src/hooks/useDesktopMode.ts
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Пустой массив зависимостей не панацея вообще

2022-10-24 15:04 UTC, sablevsky commented on src/hooks/useDesktopMode.ts
> +  setMobileMode();
шляпа какая-то. У тебя каждый ререндер будет сетиться стор

2022-10-24 15:04 UTC, sablevsky commented on src/hooks/useDesktopMode.ts
> +export const useDesktopMode = () => {
нет типизации

2022-10-24 15:04 UTC, sablevsky commented on src/constants/common.ts
> +export const DESKTOP = 'desktop';
это надо в енамы запихать

2022-10-24 15:04 UTC, sablevsky commented on src/components/NFTCard/NFTCard.tsx
> +// eslint-disable-next-line react/display-name
Проблемы линтера так не решаются

2022-10-24 15:04 UTC, sablevsky commented on src/components/Modal/mobile/Modal.tsx
>    closeModal?: (arg: (value) => boolean) => void;
на аргументы нужна типизация

2022-10-24 15:04 UTC, sablevsky commented on src/components/Modal/mobile/Modal.tsx
> +import { FC, useEffect, memo } from 'react';
Честно, реализация через порталы такая себе. Мне не нравится. У тебя все равно не может быть открыто больше одной такой модалки за раз.
Слишком как-то усложненно и макаронно получается

2022-10-24 15:04 UTC, sablevsky commented on src/pages/Collection/MakeOfferModal.tsx
> +  // };
Можно удалять

2022-10-24 15:04 UTC, sablevsky commented on src/components/Layout/AppLayout.tsx
> +const Layout: FC<LayoutProps> = ({
А файл так и остался называться Layout

2022-10-24 15:04 UTC, sablevsky commented on src/components/Header/index.tsx
> +  const screenMode = useSelector<ScreenTypes>(selectScreeMode);
Явное приведение надо фиксить

2022-10-24 15:04 UTC, sablevsky commented on src/components/CartSider/mobile/CartSider.tsx
> +                buy&nbsp;{cartItems.buy.length}&nbsp;
А без хтмл сущностей можно было обойтись как-то? Нечитаемо же

2022-10-24 15:04 UTC, sablevsky commented on src/components/CartSider/CartSider.tsx
> +                invalid&nbsp;{invalidItems.length}&nbsp;orders
хтмл сущности

2022-10-24 15:04 UTC, sablevsky commented on src/components/CartSider/components/BadgeButton.tsx
> +export default memo(BadgeButton);
мне кажется, ты слишком уж избыточно оборочиваешь все в memo.
Не надо так. Чтоб memo заюзать, требуются нормальные ресуры

2022-10-24 15:04 UTC, sablevsky commented on src/components/CartSider/index.tsx
> +const HEADER_HEIGHT = 56;
У тебя похожая штука есть и в цсс вроде, да?
Если так, то архитектурно некрасиво. Замесил цсс с джсом

2022-10-24 21:08 UTC, vladji commented on src/components/CartSider/components/BadgeButton.tsx
> +export default memo(BadgeButton);
ну возможно. тут тонкая грань, с одной стороны у родителя много разных состояний, которые могут меняться и этот компонент будет перерендериться каждый раз, с другой стороны он сам не очень затратный, в общем я уберу, возможно перестарался

2022-10-24 21:08 UTC, vladji commented on src/components/CartSider/index.tsx
> +const HEADER_HEIGHT = 56;
мне это надо было для этого:
`const isHeaderVisible = window.scrollY < HEADER_HEIGHT;`
что бы потом сетать нужный класс на модалку по нажатии на кнопку. не хотел повторять константу из цсс, но не придумал, как это можно было бы сделать по -другому

2022-10-24 21:08 UTC, vladji commented on src/components/CartSider/CartSider.tsx
> +                invalid&nbsp;{invalidItems.length}&nbsp;orders
ну я думал так лучше будет, чем просто пробел ставить. для меня так более читаемо. ок, уберу

2022-10-24 21:08 UTC, vladji commented on src/components/CartSider/CartSider.tsx
> +                invalid&nbsp;{invalidItems.length}&nbsp;orders
но мне кажется, что вот так все таки как-то ненадежно, этот пробел посередине кто-нить может случайно удалить
`{cartItems.buy.length} {cartItems.buy.length > 1 ? 'NFTs' : 'NFT'}`

2022-10-24 21:08 UTC, vladji commented on src/components/CartSider/mobile/CartSider.tsx
> +                buy&nbsp;{cartItems.buy.length}&nbsp;
убрал, но без удовольствия)

2022-10-24 21:08 UTC, vladji commented on src/components/Layout/AppLayout.tsx
> +const Layout: FC<LayoutProps> = ({
не совсем понял
это были танцы с бубнами, потому что линтер ругался на то, что у функции типа нет имени, это было из-за memo, я не оч понял, почему
было вот так:
`export const AppLayout: FC<LayoutProps> = memo(({`

из-за этого пришлось сделать так:
`export const AppLayout = memo(Layout);`

но я вообще решил memo убрать отсюда, мне кажется здесь он точно избыточен

2022-10-24 21:08 UTC, vladji commented on src/components/Modal/mobile/Modal.tsx
> +import { FC, useEffect, memo } from 'react';
я хотел вынести модалку за пределы компонента на всякий случай (для модалки это так и просится)
есть кейсы, когда несколько модалок может быть открыто одновременно, например cart sider на мобилке в режиме, когда добавлены нфтишки в корзину всегда торчит снизу и видна и при этом можно открыть еще бургер меню. поэтому понадобилось замыкание, что бы див для модалки создавался только при первом рендере компонента и потом возвращается уже сама модалка и ее можно перерендерить сколько угодно, тк можно там менять классы

2022-10-24 21:08 UTC, vladji commented on src/components/NFTCard/NFTCard.tsx
> +// eslint-disable-next-line react/display-name
всплыло на коммите уже, хотел побыстрее ПР уже сделать
там ругается вот так `Component definition is missing display name  react/display-name`, когда memo юзаешь, вот пример:
`export const NFTCard: FC<NFTCardProps> = memo(`

2022-10-24 21:08 UTC, vladji commented on src/components/NFTCard/NFTCard.tsx
> +// eslint-disable-next-line react/display-name
вообще это правило немного странное, вот например, что тут криминального?
`return (props) => {`
... но такая же проблема

2022-10-24 21:08 UTC, vladji commented on src/components/Modal/mobile/Modal.tsx
>    closeModal?: (arg: (value) => boolean) => void;
done

2022-10-24 21:08 UTC, vladji commented on src/pages/Collections/Collections.tsx
>    const collectionsLoading = useSelector(selectAllMarketsLoading) as boolean;
done

2022-10-24 21:08 UTC, vladji commented on src/pages/Collections/Collections.tsx
>    const markets = useSelector(selectAllMarkets) as MarketInfo[];
done

2022-10-24 21:08 UTC, vladji commented on src/state/common/reducers.ts
>  });
обсудили

2022-10-24 21:08 UTC, vladji commented on src/state/common/selectors.ts
>  );
я убрал рамду, не уверен, что понял до конца, что ты имел ввиду
исправил, проверь плиз

2022-10-24 21:08 UTC, vladji commented on src/pages/Collections/Collections.tsx
> +  const screenMode = useSelector(selectScreeMode) as ScreenTypes;
вроде сделал

2022-10-24 21:08 UTC, vladji commented on src/pages/Collection/MakeOfferModal.tsx
> +  // };
done

2022-10-24 21:08 UTC, vladji commented on src/hooks/useDesktopMode.ts
> +export const useDesktopMode = () => {
done

2022-10-24 21:08 UTC, vladji commented on src/constants/common.ts
> +export const DESKTOP = 'desktop';
done

2022-10-24 21:08 UTC, vladji commented on src/hooks/useDesktopMode.ts
> +  setMobileMode();
вообще не должно. это в router.tsx запускается один раз. в useEffect если запихнуть, то будет сначала по умолчанию грузится компонент (для desktop), а потом уже мобилка, что не очень хорошо

2022-10-24 21:08 UTC, vladji commented on src/components/Header/index.tsx
> +  const screenMode = useSelector<ScreenTypes>(selectScreeMode);
убрал

2022-10-24 21:08 UTC, vladji commented on src/hooks/useDesktopMode.ts
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
добавил зависимость, я вообще не люблю так делать, просто так вышло)

2022-10-24 21:21 UTC, vladji commented on src/pages/Collections/Collections.tsx
>    useEffect(() => {
done

2022-10-24 21:22 UTC, vladji commented on src/pages/Collections/Collections.tsx
> +  }, [searchStr, markets]);
да, торопился. переделал все, стало ок)
из 3 эффектов получился один небольшой

2022-10-25 10:31 UTC, sablevsky approved these changes

2022-10-25 10:31 UTC, sablevsky commented on src/components/CartSider/CartSider.tsx
> +                invalid&nbsp;{invalidItems.length}&nbsp;orders
для этого у нас есть ревью и тестирование)
Чтоб то, что нужно не удалялось)

2022-10-25 10:32 UTC, sablevsky commented
Подождем, что @Alexandr-Horton скажет еще

2022-10-25 11:50 UTC, Alexandr-Horton commented
В первую очередь, если открыть корзину на мобилке, то там весь контент скролиться т.к.  овервлоу не на бади. ну конечно же 2 компонента(мобилка и деск) вместо того что просто написать на цсс, столько кода ведь уйдет, и сюда же можно отнести повторение JSX  в CartSider. Не понятно зачем обернут хедар в мемо. Клик за модалкой очевидно нужен хук и он более лаконичный. модал враппер вообще не нужен. И как насчет чистых компонентов? А еще это норма, что боковое меню жмет контент?

2022-10-25 15:03 UTC, vladji commented
> В первую очередь, если открыть корзину на мобилке, то там весь контент скролиться т.к. оверфлоу не на бади. ну конечно же 2 компонента(мобилка и деск) вместо того что просто написать на цсс, столько кода ведь уйдет, и сюда же можно отнести повторение JSX в CartSider. Не понятно зачем обернут хедар в мемо. Клик за модалкой очевидно нужен хук и он более лаконичный. модал враппер вообще не нужен. И как насчет чистых компонентов?

overflow на бади ставится только тогда, когда модалка прилипает к хедеру, когда же мы долго листали вниз, а потом повесим overflow, то вернемся к началу страницы, поэтому в таком случае модалка открывается на всю высоту экрана и overflow здесь намеренно не выставляется на бади, оставил это решение за qa
2 разных компонента - тк корзина для десктопа была написана раньше и не реализована как модалка, там два разных принципа и дабы не переписывать корзину для десктопа проще было сделать так. и так не только с корзиой а и с другими элементами, тк для десктопа все писалось с использованием antd и проще для мобилки написать с нуля
JSX в CartSider для мобилки да, повторяется, как и в компоненте для десктопа и выносить в таком случае надо было по хорошему в обоих местах, не хотелось этого делать для экономии времени
Хедер в мемо меньше ререндерится - проверено. я думал, что так будет лучше
насчет хука может ты и прав, просто закрытие модалки по клику не всегда нужно и на тот момент было проще так сделать, простот передавать setState из родительского комопнента
в modalWrapper описан весь css для модалки, я не оч понимаю, как тут без него)
что имел ввиду насчет чистых компонентов? где именно?

2022-10-25 17:15 UTC, Alexandr-Horton approved these changes

2022-10-25 17:15 UTC, xhrtn commented on src/components/Modal/mobile/Modal.tsx
> +  const handleClickOutOfModal = useCallback(() => {
https://www.30secondsofcode.org/react/s/use-click-outside

2022-10-25 17:41 UTC, vladji commented on src/components/Modal/mobile/Modal.tsx
> +  const handleClickOutOfModal = useCallback(() => {
этот closeModal, который используется в handleClickOutOfModal сейчас не используется нигде, стал лишним после рефакторинга и у него не было задачи закрывать модалку при клике за ее пределами, поэтому это сейчас не имеет смысла и эту фунциюю можно вообще удалить

2022-10-31 08:29 UTC, sablevsky approved these changes

2022-10-31 09:56 UTC, Alexandr-Horton approved these changes

2022-11-01 10:19 UTC, merged