Pair creation Chart
hadeswap-solana/hadeswap-ui pull request #50
Opened 2022-10-28 16:03 UTC by Alexandr-Horton

## Description

Add react-chartjs-2, Pair creation Chart for pool page
## Screenshots

## Environment link

[Link](https://hadeswap-git-feature-DEVS-671-frakt.vercel.app/)

## Jira issue link

[DEVS-671](https://frakt-nft.atlassian.net/browse/DEVS-671)

2022-10-31 08:48 UTC, sablevsky requested changes

2022-10-31 08:48 UTC, sablevsky commented on src/components/ChartLine/ChartLine.tsx
> +interface IProps {
Я не очень катирую нейминг интерфейсов I.
У тебя идет явное связывание к реализации через интерфейс.
А ведь можно объявить через тайп.
Короче, лушче используй ChartLineProps, что-то в этом духе

2022-10-31 08:48 UTC, sablevsky commented on src/components/ChartLine/ChartLine.tsx
> +  const spotPrice = +formatBNToString(new BN(baseSpotPrice));
тут какой-то оверижиниринг)
Почему нельзя new BN().toNumber()?

2022-10-31 08:48 UTC, sablevsky commented on src/components/ChartLine/ChartLine.tsx
> +  };
тут тоже странные вычисления)

2022-10-31 08:48 UTC, sablevsky commented on src/components/ChartLine/ChartLine.tsx
> +  const amountOrder: number = buyOrdersAmount + sellOrders.length;
для таких переменных необязательно объявлять тип. И так понятно, т.к. это сумма двух чисел

2022-10-31 08:48 UTC, sablevsky commented on src/components/ChartLine/ChartLine.tsx
> +      if (i < half) return i - half;
а что будет, если условие не выполняется? 
undefined собираешь, получается?

2022-10-31 08:48 UTC, sablevsky commented on src/components/ChartLine/ChartLine.tsx
> +    .map((none, i) => {
по конвенциям лучше заменить `none` на `_`

2022-10-31 08:48 UTC, sablevsky commented on src/components/ChartLine/ChartLine.tsx
> +      else return Math.abs(i - half);
тут else не нужен)

2022-10-31 08:48 UTC, sablevsky commented on src/components/ChartLine/ChartLine.tsx
> +  const quadrants: any[] = [
полагаю, тут гемор с типизацией?
Поэтому докапываться не буду)

2022-10-31 09:49 UTC, Alexandr-Horton commented on src/components/ChartLine/ChartLine.tsx
> +      if (i < half) return i - half;
пустой массив будет

2022-10-31 09:52 UTC, Alexandr-Horton commented on src/components/ChartLine/ChartLine.tsx
> +  const spotPrice = +formatBNToString(new BN(baseSpotPrice));
потому что эта функция уже содержит в себе необходимые проверки и преобразования, это лучше, чем если бы я тоже самое написал еще раз, ради того чтобы возвращался number

2022-10-31 09:55 UTC, sablevsky commented on src/components/ChartLine/ChartLine.tsx
> +  const spotPrice = +formatBNToString(new BN(baseSpotPrice));
А, я понял почему. Ок, пусть будет так)

2022-10-31 09:56 UTC, sablevsky commented on src/components/ChartLine/ChartLine.tsx
> +  };
ок, с formatBNToString я понял.
А зачем вот это? `+((spotPrice * rawDelta) / 1e4).toFixed(2)`?
Приводить число к строке, а потом обратно в число. Не совсем понимаю

2022-10-31 09:59 UTC, sablevsky commented on src/components/ChartLine/ChartLine.tsx
> +      if (i < half) return i - half;
Я не понимаю))))
Функция-колюэк мап возвращает значение, которое попадет в новый массив. Если твое условие не срабатывает, то она вернет undefined.
Мб у меня лыжи не едут. Объясни пж)

2022-11-02 09:23 UTC, sablevsky approved these changes

2022-11-04 08:55 UTC, Alexandr-Horton commented on src/components/ChartLine/ChartLine.tsx
> +      if (i < half) return i - half;
Array() - просто вызов без значения уже создает пустой массив, а если промапить пустой массив то он пустым и останется. Попробуй в песочнице )

2022-11-04 08:59 UTC, sablevsky commented on src/components/ChartLine/ChartLine.tsx
> +      if (i < half) return i - half;
Я вроде на джсе не первый день пишу)
Если в мапе нет ретурна (в твоем случае если условие не выполняется), то по умолчанию функция возвращает undefinded
<img width="787" alt="image" src="https://user-images.githubusercontent.com/24393100/199933141-4fa420dc-181c-4210-8faa-23c04d282e1c.png">

2022-11-04 09:01 UTC, sablevsky commented on src/components/ChartLine/ChartLine.tsx
> +      if (i < half) return i - half;
Либо, ты пытаешься донести мне другой поинт. В таком случае, это неочевидный код и его надо переписать

2022-11-04 09:27 UTC, vladji commented on src/components/ChartLine/ChartLine.tsx
> +  const spotPrice = +formatBNToString(new BN(baseSpotPrice));
лично мое предпочтение не делать так, а приводить к числу типа так Number(), более наглядно, как по мне

2022-11-04 09:27 UTC, vladji commented on src/components/ChartLine/ChartLine.tsx
> +      const half = Math.ceil(priceArrayBuy.array.length);
не оч понятно, зачем тут округление

2022-11-04 09:27 UTC, vladji commented on src/pages/Pool/PoolPage.tsx
> +        }`}
у нас есть либа classNames
className={classNames(styles.generalInfo, {[styles.generalInfoFull]: isLiquidityProvisionPool} )}

2022-11-04 09:27 UTC, vladji approved these changes

2022-11-30 12:59 UTC, closed without merging