feat: reduce amount of parallel requests
hadeswap-solana/hadeswap-ui pull request #55
Opened 2022-11-02 07:44 UTC by vladji

## Description

Reducing the number of parallel queries

## Environment link

[Link](https://hadeswap-git-feature-devs-655-frakt.vercel.app/)

## Jira issue link

[DEVS-655](https://frakt-nft.atlassian.net/browse/DEVS-655)

2022-11-02 09:49 UTC, sablevsky requested changes

2022-11-02 09:49 UTC, sablevsky commented on src/requests/constants.ts
> +interface IQuery {
Я очень не люблю названия интерфейсов с I.
Ты явно привязываешь типизацию к интерфейсу. А ведь типизацию и через тип можно сделать

2022-11-02 09:49 UTC, sablevsky commented on src/requests/constants.ts
> +    cacheTime: 5 * 60 * 1000,
почитай доку. Кэш тайм это прям совсем не то, что тебе нужно. Тебе нужен staleTime

2022-11-02 09:49 UTC, sablevsky commented on src/requests/index.ts
> +
Дико переусложенная логика. Тебе все это не нужно.
staleTime было б достаточно.
queryClient нужен прям для совсем уже ниндзя-оптимизаций

2022-11-02 09:49 UTC, sablevsky commented on src/requests/index.ts
> +    cacheTime: cacheTime,
выкинуть cacheTime

2022-11-02 09:49 UTC, sablevsky commented on src/requests/constants.ts
> +import { web3 } from 'hadeswap-sdk';
если уж решил вынести типы отдельно, то лучше назови файл `types.ts`

2022-11-02 09:49 UTC, sablevsky commented on src/requests/index.ts
> +};
Да и вообще, не вижу смысла в этих обертках, если честно.
Проще определить фетч-функции и спокойно использовать useQuery в конкретных хуках:
useWalletNfts, useCollections etc.
Если нужно скомбиниовать 2 запроса -- просто сделать вызов двух внутри одного хука и там это объединить

2022-11-02 09:49 UTC, sablevsky commented on src/requests/requests.ts
> +};
тут по типизации шляпа полная

2022-11-02 14:34 UTC, vladji commented
вроде все исправил

2022-11-02 14:46 UTC, sablevsky requested changes

2022-11-02 14:46 UTC, sablevsky commented on src/requests/index.ts
> +  const walletPubkey: web3.PublicKey = useSelector(selectWalletPublicKey);
используй useWallet хук

2022-11-02 14:46 UTC, sablevsky commented on src/requests/index.ts
> +  return { data, isLoading };
как-то некрасиво выглядит. По-другому никак нельзя?
И по типизации странно

2022-11-02 14:46 UTC, sablevsky commented on src/requests/types.ts
> +}
я б вообще грохнул этот файл целиком.
Лишняя абстракция.
А данные queryKey, функцию и т.д. захардкодил напрямую в хуках

2022-11-02 14:46 UTC, sablevsky commented on src/pages/MyPools/helpers.ts
> +): Array<ReturnType<typeof combineMyPoolsPageTableInfo>> => {
это вообще как должно типизироваться? Рекурсивно?
Фигня какая-то

2022-11-02 14:46 UTC, sablevsky commented on src/requests/constants.ts
> +};
то же самое. Этот файл можно выпилить

2022-11-02 19:29 UTC, vladji commented on src/pages/MyPools/helpers.ts
> +): Array<ReturnType<typeof combineMyPoolsPageTableInfo>> => {
)))
да, это ошибка)

2022-11-02 19:29 UTC, vladji commented on src/requests/index.ts
> +  return { data, isLoading };
попробую по-другому

2022-11-02 19:29 UTC, vladji commented on src/requests/constants.ts
> +};
выпилил

2022-11-02 19:29 UTC, vladji commented on src/requests/types.ts
> +}
грохнул

2022-11-03 14:30 UTC, sablevsky approved these changes

2022-11-03 14:30 UTC, sablevsky commented on src/requests/index.ts
> +    staleTime: 5,
5ms -- маловато как-то, даже если нужны суперсвежие данные.
Меньше секунды ставить смысла нет

2022-11-03 20:16 UTC, vladji commented on src/requests/index.ts
> +    staleTime: 5,
да, я что-то не подумал. исправлю на 5 сек

2022-11-04 09:02 UTC, Alexandr-Horton approved these changes

2022-11-04 09:02 UTC, xhrtn commented on src/pages/MyPools/MyPools.tsx
> +  });
я правильно понял, что тут UseEffect без зависимостей?

2022-11-04 09:04 UTC, sablevsky commented on src/pages/MyPools/MyPools.tsx
> +  });
Опа, не заметил.
@vladji а почему?))

2022-11-04 09:30 UTC, vladji commented on src/pages/MyPools/MyPools.tsx
> +  });
да, правильно. он будет срабатывать только когда все данные загрузились, поэтому что бы не добавлять 3 зависимости туда я решил просто их не добавлять вообще

2022-11-04 09:38 UTC, vladji commented on src/pages/MyPools/MyPools.tsx
> +  });
блин, я затупил), сча добавлю)

2022-11-04 09:44 UTC, vladji commented on src/pages/MyPools/MyPools.tsx
> +  });
хотя все таки нет, я не просто так там это оставил, кое что сломалось

2022-11-04 09:52 UTC, vladji commented on src/pages/MyPools/MyPools.tsx
> +  });
короч, там если зависимость добавить, то не срабатывает, когда нужно. поэтому я убрал зависимости и добавил условие внутрь хука

2022-11-04 12:05 UTC, merged