Feature/devs 665 cart sider
hadeswap-solana/hadeswap-ui pull request #62
Opened 2022-11-08 06:53 UTC by vladji

## Description

UI update: header, cart sider, some color of layout

## Environment link

[Link](https://hadeswap-git-feature-devs-665-cart-sider-frakt.vercel.app/)

## Jira issue link

[DEVS-665](https://frakt-nft.atlassian.net/browse/DEVS-665)

2022-11-09 09:24 UTC, sablevsky requested changes

2022-11-09 09:24 UTC, sablevsky commented on src/pages/EditPool/EditPool.tsx
> +  console.log('EDIT-pool');
npm run prepare забыл
Каким-то образом хаски это пропустил
Удалить console.log, очевидно

2022-11-09 09:24 UTC, sablevsky commented on src/components/Buttons/Button.tsx
> +      onClick={!isDisabled ? onClick : undefined}
Я не люблю, когда явно используется андефайнд)
Он на то и андефайнд, что неопределен. Логическая несостыковка, правда? Поэтому, где нужно пустое значение, надо юзать null

2022-11-09 09:24 UTC, sablevsky commented on src/components/Buttons/DeleteButton.tsx
> +    className={classNames(styles.deleteButton, { [className]: className })}
Можно просто передавать className, если оно falsy, то все отлично отработает без сложного объектного синтаксиса

2022-11-09 09:24 UTC, sablevsky commented on src/components/Buttons/RoundIconButton.tsx
> +    className={classNames(styles.roundIconWrapper, { [className]: className })}
тут то же самое с className

2022-11-09 09:24 UTC, sablevsky commented on src/components/Buttons/styles.module.scss
> +  cursor: default;
а зачем default?
Чем дефолтный disabled курсор не устроил?

2022-11-09 09:24 UTC, sablevsky commented on src/components/Buttons/styles.module.scss
> +  font-feature-settings: 'tnum' on, 'lnum' on;
а эт что?)

2022-11-09 09:24 UTC, sablevsky commented on src/components/Buttons/styles.module.scss
> +}
Кстати, настрой у себя в среде линтер на css/scss. Гит не очень любит, когда файл не заканчивается переводом строки
<img width="122" alt="image" src="https://user-images.githubusercontent.com/24393100/200786727-746bcbf9-093c-4733-a949-63d9ce3ce07e.png">

2022-11-09 09:24 UTC, sablevsky commented on src/components/CartSider/CartSider.tsx
> +
Плохой код. Тяжело читается. Логическое И внутри if'а, зачем?
Переписать.
Я б вообще в отдельный хук вынес

2022-11-09 09:24 UTC, sablevsky commented on src/components/CartSider/CartSider.tsx
> +  }, []);
тут тоже. У тебя зависимость на setHeigt. Либо объявляй функцию вне компонента, либо заворачвай в useCallback

2022-11-09 09:24 UTC, sablevsky commented on src/components/CartSider/CartSider.tsx
> +          }`}
я б повыносил названия такие длинные в отдельные переменные

2022-11-09 09:24 UTC, sablevsky commented on src/components/CartSider/components/Card.tsx
> +      <SolPrice className={styles.cardPrice} price={Number(price)} />
лучше юзать parseFloat

2022-11-09 09:24 UTC, sablevsky commented on src/components/CartSider/components/CartSectionInvalid.tsx
> +  dispatch: (arg: ReturnType<typeof coreActions.clearInvalidOrders>) => void;
Уверен? А почему нельзя просто заюзать dispatch+actionCreator внутри?
Вместо каких-то сложнотипизированных пропсов?

2022-11-09 09:24 UTC, sablevsky commented on src/components/CartSider/components/styles.module.scss
> +  }
а почему нельзя всем сделать mb 32px и убрать у последнего чилда?
Без этих непонятных инверсий через not?

2022-11-09 09:24 UTC, sablevsky commented on src/components/CartSider/index.tsx
> +  setShowModal?: (arg: (value: boolean) => boolean) => void;
а почему функция как аргумент?

2022-11-09 09:24 UTC, sablevsky commented on src/components/Search/index.tsx
> +export default Index;
Почему папка компонента называется Search, а сам компонент Index?
Index плохое название btw

2022-11-09 09:24 UTC, sablevsky commented on src/components/SolPrice/SolPrice.tsx
> +      {price ? (raw ? (price / 1e9).toFixed(3) : price) : 0}
тернарник внутри тернарника. Невозможно читать же. Надо переписать

2022-11-10 16:41 UTC, vladji commented on src/components/Buttons/Button.tsx
> +      onClick={!isDisabled ? onClick : undefined}
да, я тоже) 
не спрашивай, почему я так сделал)
поменял на null

2022-11-10 16:41 UTC, vladji commented on src/components/Buttons/DeleteButton.tsx
> +    className={classNames(styles.deleteButton, { [className]: className })}
ок, поменял

2022-11-10 16:41 UTC, vladji commented on src/components/Buttons/RoundIconButton.tsx
> +    className={classNames(styles.roundIconWrapper, { [className]: className })}
поменял

2022-11-10 16:41 UTC, vladji commented on src/components/Buttons/styles.module.scss
> +  cursor: default;
обсудили

2022-11-10 16:41 UTC, vladji commented on src/components/Buttons/styles.module.scss
> +  font-feature-settings: 'tnum' on, 'lnum' on;
тестил, забыл убрать)

2022-11-10 16:41 UTC, vladji commented on src/components/Buttons/styles.module.scss
> +}
да, я знаю. обычно руками добавляю) посмотрю

2022-11-10 16:41 UTC, vladji commented on src/components/CartSider/CartSider.tsx
> +
убрал эту логику вообще, она не нужна уже

2022-11-10 16:41 UTC, vladji commented on src/components/CartSider/CartSider.tsx
> +  }, []);
убрал эту логику

2022-11-10 16:41 UTC, vladji commented on src/components/CartSider/CartSider.tsx
> +          }`}
done

2022-11-10 16:41 UTC, vladji commented on src/components/CartSider/components/Card.tsx
> +      <SolPrice className={styles.cardPrice} price={Number(price)} />
согласен)

2022-11-10 16:41 UTC, vladji commented on src/components/CartSider/components/CartSectionInvalid.tsx
> +  dispatch: (arg: ReturnType<typeof coreActions.clearInvalidOrders>) => void;
переделал

2022-11-10 16:41 UTC, vladji commented on src/components/CartSider/components/styles.module.scss
> +  }
ок, сделаю так

2022-11-10 16:41 UTC, vladji commented on src/components/CartSider/index.tsx
> +  setShowModal?: (arg: (value: boolean) => boolean) => void;
переделал
`setShowModal?: (func: React.Dispatch<React.SetStateAction<boolean>>) => void;`

2022-11-10 16:41 UTC, vladji commented on src/components/Search/index.tsx
> +export default Index;
это в webstorme когда рефакторинг делаешь он переименовывает автоматом, не усмотрел

2022-11-10 16:41 UTC, vladji commented on src/components/SolPrice/SolPrice.tsx
> +      {price ? (raw ? (price / 1e9).toFixed(3) : price) : 0}
это не я писал)
переделаю

2022-11-10 16:41 UTC, vladji commented on src/pages/EditPool/EditPool.tsx
> +  console.log('EDIT-pool');
угу

2022-11-14 16:30 UTC, sablevsky approved these changes

2022-11-14 16:30 UTC, sablevsky commented on src/components/CartSider/index.tsx
> +  setShowModal?: (arg: (value: boolean) => boolean) => void;
Dispatch<SetStateAction<Boolean>>

2022-11-14 17:54 UTC, merged